---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
  become: yes
 
- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  become: yes

- name: install pre-requisites
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ netdata_script_dependencies }}"
  become: yes

- name: Copy netdata repository file
  copy:
    src: netdata_netdata.repo
    dest: /etc/yum.repos.d/netdata_netdata.repo
  become: yes

- name: Install netdata
  yum:
    enablerepo: "netdata_netdata"
    name: netdata-1.19.0-1.el7.x86_64
    state: present
    update_cache: true
  become: yes
